# Imports

In [36]:
import sympy as sp
import numpy as np

# Problem 5

## Part (a)

In [24]:
x = np.array([3,-4,0,3/2])
print('1-norm:   %.2f'%np.linalg.norm(x,ord=1))
print('2-norm:   %.2f'%np.linalg.norm(x,ord=2))
print('inf-norm: %.2f'%np.linalg.norm(x,ord=np.inf))

1-norm:   8.50
2-norm:   5.22
inf-norm: 4.00


## Part (b)

In [8]:
A = sp.Matrix([[2,-1,0],[-1,2,-1],[0,-1,2]])
lam = sp.Symbol(r'\lambda')

In [15]:
temp = A.T*A
print(sp.latex(temp))
display(temp)
temp -= lam*sp.eye(3)
display(temp)
temp = temp.det()
print(sp.latex(temp))
display(temp)
temp = sp.solve(temp,lam)
display(temp)
(A.T*A).eigenvals()

\left[\begin{matrix}5 & -4 & 1\\-4 & 6 & -4\\1 & -4 & 5\end{matrix}\right]


Matrix([
[ 5, -4,  1],
[-4,  6, -4],
[ 1, -4,  5]])

Matrix([
[5 - \lambda,          -4,           1],
[         -4, 6 - \lambda,          -4],
[          1,          -4, 5 - \lambda]])

- \lambda^{3} + 16 \lambda^{2} - 52 \lambda + 16


-\lambda**3 + 16*\lambda**2 - 52*\lambda + 16

[4, 6 - 4*sqrt(2), 4*sqrt(2) + 6]

{4: 1, 6 - 4*sqrt(2): 1, 4*sqrt(2) + 6: 1}

In [23]:
A = np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
print('1-norm:   %.2f'%np.linalg.norm(A,ord=1))
print('2-norm:   %.2f'%np.linalg.norm(A,ord=2))
print('inf-norm: %.2f'%np.linalg.norm(A,ord=np.inf))

1-norm:   4.00
2-norm:   3.41
inf-norm: 4.00


# Problem 6

## Part (a)

In [51]:
A = sp.Matrix([[3,0],[0,-2]])
lam = sp.Symbol(r'\lambda')

In [57]:
temp = A.T*A
print(sp.latex(temp))
display(temp)
temp = (temp - lam*sp.eye(2)).det()
print(sp.latex(temp.simplify()))
display(temp.simplify())
temp = sp.solve(temp)
display(temp)
(A.T*A).diagonalize()

\left[\begin{matrix}9 & 0\\0 & 4\end{matrix}\right]


Matrix([
[9, 0],
[0, 4]])

\lambda^{2} - 13 \lambda + 36


\lambda**2 - 13*\lambda + 36

[4, 9]

(Matrix([
 [0, 1],
 [1, 0]]),
 Matrix([
 [4, 0],
 [0, 9]]))

In [65]:
A = np.array([[3,0],[0,-2]])
U,Sig,Vt = np.linalg.svd(A,full_matrices=True)

In [66]:
print('U={} \n\n Sigma={} \n\n V*={}'.format(U,Sig,Vt))

U=[[1. 0.]
 [0. 1.]] 

 Sigma=[3. 2.] 

 V*=[[ 1.  0.]
 [-0. -1.]]


## Part (b)

In [61]:
A = sp.Matrix([[0,2],[0,0],[0,0],[0,0]])
display(A.T*A)

Matrix([
[0, 0],
[0, 4]])

In [60]:
(A.T*A).diagonalize()

(Matrix([
 [1, 0],
 [0, 1]]),
 Matrix([
 [0, 0],
 [0, 4]]))

In [62]:
A = np.array([[0,2],[0,0],[0,0],[0,0]])
U,Sig,Vt = np.linalg.svd(A,full_matrices=True)

In [63]:
print('U={} \n\n Sigma={} \n\n V*={}'.format(U,Sig,Vt))

U=[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

 Sigma=[2. 0.] 

 V*=[[ 0.  1.]
 [-1.  0.]]
